close #11
coollectica/PracticaEvCont2 pull request #27
Opened 2020-02-05 09:08 UTC by Severus-12

2020-02-05 11:27 UTC, temple requested changes

2020-02-05 11:27 UTC, temple commented on actividad2.js
>  //4.2 Acceso a una posición de un array
El título que sea el de el enunciado

2020-02-05 11:27 UTC, temple commented on actividad2.js
> +el acceso a la posición del array se produce en la linea 2343. En el slideItems[0].
hay que aclarar que el array es `slideItems` y que la posición accedida es la `0` y que por eso se emplea la sintaxis array[posicion] quedando `slideItems[0]`

2020-02-07 10:01 UTC, bitcoinoperated commented
```

/* 4.2 Fragmento de código donde aparezca el acceso a una posición de un array.
      LÍNEAS 330-336.
      En la línea 330 podemos ver la creación de la función con el parámetro "nl" que pretende crear una lista de nodos ("matriz") de algún objeto.
      En la línea 331 podemos ver la creación de una "array" vacía llamada "arr".
      En la línea 332 podemos ver el uso de la declaración "for" que crea un bucle que recorre la lista de nodos adquiridos.
      Luego se accede a la "array" "arr" y se inserta la lista de nodos adquiridos dentro.
      En la línea 335, la declaración "return" finaliza la función y devuelve los valores de la array "arr".
      Podemos ver la documentación de MDN de objeto "array" y declaracion "for" en estas enlaces:
      https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array      
      https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for */

        function arrayFromNodeList (nl) {
          var arr = [];
          for (var i = 0, l = nl.length; i < l; i++) {
            arr.push(nl[i]);
          }
          return arr;
        }

```

2020-02-07 11:45 UTC, temple approved these changes

2020-02-07 11:45 UTC, temple commented on actividad2.js
> +El array es slideItems y la posición accedida es la 0;  por eso se emplea la sintaxis array[posicion] quedando slideItems[0].*/
80 chars per line máximo.
Añadir referencia documental

2020-02-07 11:47 UTC, merged